#########################################################################################################################################
#
#
# ░██████╗████████╗░█████╗░████████╗██╗░██████╗████████╗██╗░█████╗░░██████╗
# ██╔════╝╚══██╔══╝██╔══██╗╚══██╔══╝██║██╔════╝╚══██╔══╝██║██╔══██╗██╔════╝
# ╚█████╗░░░░██║░░░███████║░░░██║░░░██║╚█████╗░░░░██║░░░██║██║░░╚═╝╚█████╗░
# ░╚═══██╗░░░██║░░░██╔══██║░░░██║░░░██║░╚═══██╗░░░██║░░░██║██║░░██╗░╚═══██╗
# ██████╔╝░░░██║░░░██║░░██║░░░██║░░░██║██████╔╝░░░██║░░░██║╚█████╔╝██████╔╝
#  ╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░░╚═╝░░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═════╝░
#
# Commands:
#
# Global Placeholders:
# %zahstats_item_sold_amount% - The number of items listed for sale.
# %zahstats_item_purchase_amount% - The number of items purchased.
# %zahstats_number_of_items_not_sold% - The number of unsold items that will expire.
# %zahstats_number_of_items_expired% - The number of items that have expired.
# %zahstats_number_of_items_remove_from_expire% - The number of items removed from the EXPIRE storage type.
# %zahstats_number_of_items_remove_from_storage% - The number of items removed from the ITEMS storage type.
# %zahstats_number_of_items_remove_from_bought% - The number of items removed from the BUY storage type.
# %zahstats_number_of_items_destroy% - The number of items that have been destroyed.
# %zahstats_auction_opened% - The number of times the auction house was opened.
#
# Global Economy Placeholders:
# %zahstats_money_spend_<economy name>% - Total money spent in the auction house.
# %zahstats_total_price_of_all_items_sold_<economy name>% - Cumulative price of all items that were listed for sale.
# %zahstats_money_spend_format_<economy name>% - Total money spent in the auction house.
# %zahstats_total_price_of_all_items_sold_format_<economy name>% - Cumulative price of all items that were listed for sale.
#
# Player Placeholders:
# %zahstats_player_total_sales% - Total items on sale
# %zahstats_player_total_purchases% - Total items purchased
# %zahstats_player_total_sales_format% - Total items on sale formatted
# %zahstats_player_total_purchases_format% - Total items purchased formatted
# %zahstats_player_total_earned_<economy name>% - Total money earned
# %zahstats_player_total_spent_<economy name>% - Total money spent
# %zahstats_player_total_format_earned_<economy name>% - Total money earned formatted
# %zahstats_player_total_format_spent_<economy name>% - Total money spent formatted
#
# Ranking Placeholders:
# %zahstats_who_spent_most_money_name_<economy name>% - Who spent the most - Name
# %zahstats_who_spent_most_money_amount_<economy name>% - Who spent the most - Amount
# %zahstats_who_earned_most_money_name_<economy name>% - Who earned the most - Name
# %zahstats_who_earned_most_money_amount_<economy name>% - Who earned the most - Amount
# %zahstats_who_purchased_most_items_name_<economy name>% - Who purchased the most - Name
# %zahstats_who_purchased_most_items_amount_<economy name>% - Who purchased the most - Amount
# %zahstats_who_sales_most_items_name_<economy name>% - Who sales the most - Name
# %zahstats_who_sales_most_items_amount_<economy name>% - Who sales the most - Amount
# %zahstats_who_purchased_most_items_name% - Who purchased the most - Name
# %zahstats_who_purchased_most_items_amount% - Who purchased the most - Amount
# %zahstats_who_sales_most_items_name% - Who sales the most - Name
# %zahstats_who_sales_most_items_amount% - Who sales the most - Amount
#
#########################################################################################################################################

# Displays more information in the console, if you have a problem please enable this option and send errors to support.
enableDebug: false

# Enables time debugs, is used to measure plugin performance
enableDebugTime: false

sql:
  host: 192.168.10.10
  port: 3306
  user: homestead
  password: 'secret'
  database: zauctionhouse

noName: "✘"
noAmount: "0"